/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Reportes;

import java.awt.HeadlessException;
import formularios.ConexionTienda;
import formularios.FramePrincipal;
import formularios.Menu;
import java.sql.*;
import java.util.Map;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JRViewer;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.commons.collections.map.HashedMap;

/**
 *
 * @author PC
 */
public class ReporteVentas extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReporteVentas
     */
    public ReporteVentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void imprimirReporte() throws HeadlessException {
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            ConexionTienda cc = new ConexionTienda();
            Connection cn = cc.conectar();
            Map parametros = new HashedMap();
            if (jComboBox1.getSelectedItem().equals("CÓDIGO")) {
                parametros.put("codigo", jTextField_Reportes.getText());
                JasperReport reporte = JasperCompileManager.compileReport("src\\Reportes\\reporteAutoxPlaca.jrxml");
                JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);
                JInternalFrame frame = new JInternalFrame("Reporte");
                frame.getContentPane().add(new JRViewer(imprimir));
                frame.pack();
                frame.setResizable(true);
                frame.setClosable(true);
                frame.setMaximizable(true);
                frame.setSize(1000, 700);
                Menu.jDesktopPane1.add(frame);
                frame.setVisible(true);
            }
            if (jComboBox1.getSelectedItem().equals("TIPO")) {
                parametros.put("tipo", jTextField_Reportes.getText());
                JasperReport reporte = JasperCompileManager.compileReport("src\\reportes\\reporteAutoxModelo.jrxml");
                JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);
                JInternalFrame frame = new JInternalFrame("Reporte");
                frame.getContentPane().add(new JRViewer(imprimir));
                frame.pack();
                frame.setResizable(true);
                frame.setClosable(true);
                frame.setMaximizable(true);
                frame.setSize(1000, 700);
                Menu.jDesktopPane1.add(frame);
                frame.setVisible(true);
            }
            if (jComboBox1.getSelectedItem().equals("MARCA")) {
                parametros.put("marca", jTextField_Reportes.getText());
                JasperReport reporte = JasperCompileManager.compileReport("src\\reportes\\reporteAutoxMarca.jrxml");
                JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);
                JInternalFrame frame = new JInternalFrame("Reporte");
                frame.getContentPane().add(new JRViewer(imprimir));
                frame.pack();
                frame.setResizable(true);
                frame.setClosable(true);
                frame.setMaximizable(true);
                frame.setSize(1000, 700);
                Menu.jDesktopPane1.add(frame);
                frame.setVisible(true);
            }
            if (jComboBox1.getSelectedItem().equals("FECHA")) {
                parametros.put("fecha", jTextField_Reportes.getText());
                JasperReport reporte = JasperCompileManager.compileReport("src\\reportes\\reporteAutoxAño.jrxml");
                JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);
                JInternalFrame frame = new JInternalFrame("Reporte");
                frame.getContentPane().add(new JRViewer(imprimir));
                frame.pack();
                frame.setResizable(true);
                frame.setClosable(true);
                frame.setMaximizable(true);
                frame.setSize(1000, 700);
                Menu.jDesktopPane1.add(frame);
                frame.setVisible(true);
            }
            if (jComboBox1.getSelectedItem().equals("SELECCIONE")) {
                JOptionPane.showMessageDialog(null, "SELECCIONE OPCION");
            }
            if (jComboBox1.getSelectedItem().equals("GENERAL")) {
//                parametros.put("año", txtReportes.getText());
                JasperReport reporte = JasperCompileManager.compileReport("src\\reportes\\reporteAuto.jrxml");
                JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);
                JInternalFrame frame = new JInternalFrame("Reporte");
                frame.getContentPane().add(new JRViewer(imprimir));
                frame.pack();
                frame.setResizable(true);
                frame.setClosable(true);
                frame.setMaximizable(true);
                frame.setSize(1000, 700);
                Menu.jDesktopPane1.add(frame);
                frame.setVisible(true);
            }


            //JasperViewer.viewReport(imprimir,false);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "1" + ex);
        }
    }
    
    public static void main(String args[]) {
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
                new ReporteVentas().setVisible(true);
            }
        });
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField_Reportes = new javax.swing.JTextField();
        jButton_Reporte = new javax.swing.JButton();

        jLabel1.setText("Buscar por: ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton_Reporte.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField_Reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Reporte)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Reportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Reporte))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Reporte;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField_Reportes;
    // End of variables declaration//GEN-END:variables
}
